#!/bin/sh

DAEMON=/usr/sbin/stalkd
NAME=stalk
DESC=STALK

test -x $DAEMON || exit 0
set -e

case "$1" in
	start)
		echo -n "Starting $DESC... "
		start-stop-daemon --start --background --m --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON || true
		;;

	stop)
		echo -n "Stopping $DESC..."
		start-stop-daemon --stop --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON || true
		;;

	restart|force-reload)
		echo -n "Restarting $DESC... "
		start-stop-daemon --stop --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON || true
		sleep 1
		start-stop-daemon --start --background --m  --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON || true
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" stalk && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
